title: PL Conference Deadlines
description: Countdowns to top PL venue deadlines
author: Yichen Xu

domain: "www.pl-deadlines.info"
baseurl: ""

twitter_hashtag: machinelearning
github_username: linyxus
github_repo: pl-deadlines

markdown: kramdown
ga_id:

include: ['_pages']

repository: linyxus/pl-deadlines

